server:
  port: 7778

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: malwareGroup
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: localhost:9092

    template:
      default-topic: malware-scanner

  application:
    name: malware-scanner